# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0266903e6bdd1744c8cea256d89ff230"
extension_directories = [ ]
name = "Import Pilot"
application_url = "https://import-pilot-production.up.railway.app/app"
embedded = true
handle = "import-pilot-official"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [
  "app/uninstalled",
  "bulk_operations/finish",
  "inventory_items/update",
  "products/delete",
  "products/update"
]
  uri = "https://import-pilot-production.up.railway.app/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_channels,write_channels,write_inventory,read_inventory,read_locations,read_markets,write_markets,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,read_product_listings,write_product_listings,read_products,write_products,read_script_tags,write_script_tags"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://import-pilot-production.up.railway.app/auth/callback"
]
