import { type RouteConfig, route, index } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("auth/login", "routes/auth.login.tsx"),
  route("auth/*", "routes/auth.$.tsx"),
  route("webhooks", "routes/webhooks.tsx"),
  route("webhooks/telegram", "routes/webhooks.telegram.tsx"),
  route("api/upload", "routes/api.upload.tsx"),
  route("api/support", "routes/api.support.tsx"),
  route("api/heartbeat", "routes/api.heartbeat.tsx"),
  route("api/upload-serve", "routes/api.upload-serve.tsx"),
  route("api/csv-options", "routes/api.csv-options.tsx"),
  route("api/filter", "routes/api.filter.tsx"),
  route("api/import", "routes/api.import.tsx"),
  route("api/import-queue", "routes/api.import-queue.tsx"),
  route("api/import-status", "routes/api.import-status.tsx"),
  route("api/preview", "routes/api.preview.tsx"),
  route("api/locations", "routes/api.locations.tsx"),
  route("api/product-types", "routes/api.product-types.tsx"),
  route("api/rule-preview", "routes/api.rule-preview.tsx"),
  route("app", "routes/app.tsx", [
    index("routes/app._index.tsx"),
    route("queue", "routes/app.queue.tsx"),
    route("duplicates", "routes/app.duplicates.tsx"),
    route("settings", "routes/app.settings.tsx"),
    route("billing", "routes/app.billing.tsx"),
    route("support", "routes/app.support.tsx"),
    route("supplier/:id", "routes/app.supplier.$id.tsx", [
      index("routes/app.supplier.$id._index.tsx"),
      route("config", "routes/app.supplier.$id.config.tsx"),
      route("columns", "routes/app.supplier.$id.columns.tsx"),
      route("price-rules", "routes/app.supplier.$id.price-rules.tsx"),
      route("category-mapping", "routes/app.supplier.$id.category-mapping.tsx"),
      route("preview", "routes/app.supplier.$id.preview.tsx"),
      route("logs", "routes/app.supplier.$id.logs.tsx"),
      route("import", "routes/app.supplier.$id.import.tsx"),
    ]),
    route("tutorial", "routes/app.tutorial.tsx"),
    route("tutorial/dashboard", "routes/app.tutorial-dashboard.tsx"),
    route("tutorial/supplier/:section", "routes/app.tutorial-supplier.$section.tsx"),
    route("tutorial/settings", "routes/app.tutorial-settings.tsx"),
    route("tutorial/duplicates", "routes/app.tutorial-duplicates.tsx"),
    route("tutorial/queue", "routes/app.tutorial-queue.tsx"),
  ]),
] satisfies RouteConfig;
