// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/webhooks": {
    params: {};
  };
  "/webhooks/telegram": {
    params: {};
  };
  "/api/upload": {
    params: {};
  };
  "/api/support": {
    params: {};
  };
  "/api/heartbeat": {
    params: {};
  };
  "/api/upload-serve": {
    params: {};
  };
  "/api/csv-options": {
    params: {};
  };
  "/api/filter": {
    params: {};
  };
  "/api/import": {
    params: {};
  };
  "/api/import-queue": {
    params: {};
  };
  "/api/import-status": {
    params: {};
  };
  "/api/preview": {
    params: {};
  };
  "/api/locations": {
    params: {};
  };
  "/api/product-types": {
    params: {};
  };
  "/api/rule-preview": {
    params: {};
  };
  "/app": {
    params: {};
  };
  "/app/queue": {
    params: {};
  };
  "/app/duplicates": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/billing": {
    params: {};
  };
  "/app/support": {
    params: {};
  };
  "/app/supplier/:id": {
    params: {
      "id": string;
    };
  };
  "/app/supplier/:id/config": {
    params: {
      "id": string;
    };
  };
  "/app/supplier/:id/columns": {
    params: {
      "id": string;
    };
  };
  "/app/supplier/:id/price-rules": {
    params: {
      "id": string;
    };
  };
  "/app/supplier/:id/category-mapping": {
    params: {
      "id": string;
    };
  };
  "/app/supplier/:id/preview": {
    params: {
      "id": string;
    };
  };
  "/app/supplier/:id/logs": {
    params: {
      "id": string;
    };
  };
  "/app/supplier/:id/import": {
    params: {
      "id": string;
    };
  };
  "/app/tutorial": {
    params: {};
  };
  "/app/tutorial/dashboard": {
    params: {};
  };
  "/app/tutorial/supplier/:section": {
    params: {
      "section": string;
    };
  };
  "/app/tutorial/settings": {
    params: {};
  };
  "/app/tutorial/duplicates": {
    params: {};
  };
  "/app/tutorial/queue": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/login" | "/auth/*" | "/webhooks" | "/webhooks/telegram" | "/api/upload" | "/api/support" | "/api/heartbeat" | "/api/upload-serve" | "/api/csv-options" | "/api/filter" | "/api/import" | "/api/import-queue" | "/api/import-status" | "/api/preview" | "/api/locations" | "/api/product-types" | "/api/rule-preview" | "/app" | "/app/queue" | "/app/duplicates" | "/app/settings" | "/app/billing" | "/app/support" | "/app/supplier/:id" | "/app/supplier/:id/config" | "/app/supplier/:id/columns" | "/app/supplier/:id/price-rules" | "/app/supplier/:id/category-mapping" | "/app/supplier/:id/preview" | "/app/supplier/:id/logs" | "/app/supplier/:id/import" | "/app/tutorial" | "/app/tutorial/dashboard" | "/app/tutorial/supplier/:section" | "/app/tutorial/settings" | "/app/tutorial/duplicates" | "/app/tutorial/queue";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/webhooks.tsx": {
    id: "routes/webhooks";
    page: "/webhooks";
  };
  "routes/webhooks.telegram.tsx": {
    id: "routes/webhooks.telegram";
    page: "/webhooks/telegram";
  };
  "routes/api.upload.tsx": {
    id: "routes/api.upload";
    page: "/api/upload";
  };
  "routes/api.support.tsx": {
    id: "routes/api.support";
    page: "/api/support";
  };
  "routes/api.heartbeat.tsx": {
    id: "routes/api.heartbeat";
    page: "/api/heartbeat";
  };
  "routes/api.upload-serve.tsx": {
    id: "routes/api.upload-serve";
    page: "/api/upload-serve";
  };
  "routes/api.csv-options.tsx": {
    id: "routes/api.csv-options";
    page: "/api/csv-options";
  };
  "routes/api.filter.tsx": {
    id: "routes/api.filter";
    page: "/api/filter";
  };
  "routes/api.import.tsx": {
    id: "routes/api.import";
    page: "/api/import";
  };
  "routes/api.import-queue.tsx": {
    id: "routes/api.import-queue";
    page: "/api/import-queue";
  };
  "routes/api.import-status.tsx": {
    id: "routes/api.import-status";
    page: "/api/import-status";
  };
  "routes/api.preview.tsx": {
    id: "routes/api.preview";
    page: "/api/preview";
  };
  "routes/api.locations.tsx": {
    id: "routes/api.locations";
    page: "/api/locations";
  };
  "routes/api.product-types.tsx": {
    id: "routes/api.product-types";
    page: "/api/product-types";
  };
  "routes/api.rule-preview.tsx": {
    id: "routes/api.rule-preview";
    page: "/api/rule-preview";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/queue" | "/app/duplicates" | "/app/settings" | "/app/billing" | "/app/support" | "/app/supplier/:id" | "/app/supplier/:id/config" | "/app/supplier/:id/columns" | "/app/supplier/:id/price-rules" | "/app/supplier/:id/category-mapping" | "/app/supplier/:id/preview" | "/app/supplier/:id/logs" | "/app/supplier/:id/import" | "/app/tutorial" | "/app/tutorial/dashboard" | "/app/tutorial/supplier/:section" | "/app/tutorial/settings" | "/app/tutorial/duplicates" | "/app/tutorial/queue";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.queue.tsx": {
    id: "routes/app.queue";
    page: "/app/queue";
  };
  "routes/app.duplicates.tsx": {
    id: "routes/app.duplicates";
    page: "/app/duplicates";
  };
  "routes/app.settings.tsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app.billing.tsx": {
    id: "routes/app.billing";
    page: "/app/billing";
  };
  "routes/app.support.tsx": {
    id: "routes/app.support";
    page: "/app/support";
  };
  "routes/app.supplier.$id.tsx": {
    id: "routes/app.supplier.$id";
    page: "/app/supplier/:id" | "/app/supplier/:id/config" | "/app/supplier/:id/columns" | "/app/supplier/:id/price-rules" | "/app/supplier/:id/category-mapping" | "/app/supplier/:id/preview" | "/app/supplier/:id/logs" | "/app/supplier/:id/import";
  };
  "routes/app.supplier.$id._index.tsx": {
    id: "routes/app.supplier.$id._index";
    page: "/app/supplier/:id";
  };
  "routes/app.supplier.$id.config.tsx": {
    id: "routes/app.supplier.$id.config";
    page: "/app/supplier/:id/config";
  };
  "routes/app.supplier.$id.columns.tsx": {
    id: "routes/app.supplier.$id.columns";
    page: "/app/supplier/:id/columns";
  };
  "routes/app.supplier.$id.price-rules.tsx": {
    id: "routes/app.supplier.$id.price-rules";
    page: "/app/supplier/:id/price-rules";
  };
  "routes/app.supplier.$id.category-mapping.tsx": {
    id: "routes/app.supplier.$id.category-mapping";
    page: "/app/supplier/:id/category-mapping";
  };
  "routes/app.supplier.$id.preview.tsx": {
    id: "routes/app.supplier.$id.preview";
    page: "/app/supplier/:id/preview";
  };
  "routes/app.supplier.$id.logs.tsx": {
    id: "routes/app.supplier.$id.logs";
    page: "/app/supplier/:id/logs";
  };
  "routes/app.supplier.$id.import.tsx": {
    id: "routes/app.supplier.$id.import";
    page: "/app/supplier/:id/import";
  };
  "routes/app.tutorial.tsx": {
    id: "routes/app.tutorial";
    page: "/app/tutorial";
  };
  "routes/app.tutorial-dashboard.tsx": {
    id: "routes/app.tutorial-dashboard";
    page: "/app/tutorial/dashboard";
  };
  "routes/app.tutorial-supplier.$section.tsx": {
    id: "routes/app.tutorial-supplier.$section";
    page: "/app/tutorial/supplier/:section";
  };
  "routes/app.tutorial-settings.tsx": {
    id: "routes/app.tutorial-settings";
    page: "/app/tutorial/settings";
  };
  "routes/app.tutorial-duplicates.tsx": {
    id: "routes/app.tutorial-duplicates";
    page: "/app/tutorial/duplicates";
  };
  "routes/app.tutorial-queue.tsx": {
    id: "routes/app.tutorial-queue";
    page: "/app/tutorial/queue";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/webhooks": typeof import("./app/routes/webhooks.tsx");
  "routes/webhooks.telegram": typeof import("./app/routes/webhooks.telegram.tsx");
  "routes/api.upload": typeof import("./app/routes/api.upload.tsx");
  "routes/api.support": typeof import("./app/routes/api.support.tsx");
  "routes/api.heartbeat": typeof import("./app/routes/api.heartbeat.tsx");
  "routes/api.upload-serve": typeof import("./app/routes/api.upload-serve.tsx");
  "routes/api.csv-options": typeof import("./app/routes/api.csv-options.tsx");
  "routes/api.filter": typeof import("./app/routes/api.filter.tsx");
  "routes/api.import": typeof import("./app/routes/api.import.tsx");
  "routes/api.import-queue": typeof import("./app/routes/api.import-queue.tsx");
  "routes/api.import-status": typeof import("./app/routes/api.import-status.tsx");
  "routes/api.preview": typeof import("./app/routes/api.preview.tsx");
  "routes/api.locations": typeof import("./app/routes/api.locations.tsx");
  "routes/api.product-types": typeof import("./app/routes/api.product-types.tsx");
  "routes/api.rule-preview": typeof import("./app/routes/api.rule-preview.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
  "routes/app.queue": typeof import("./app/routes/app.queue.tsx");
  "routes/app.duplicates": typeof import("./app/routes/app.duplicates.tsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.tsx");
  "routes/app.billing": typeof import("./app/routes/app.billing.tsx");
  "routes/app.support": typeof import("./app/routes/app.support.tsx");
  "routes/app.supplier.$id": typeof import("./app/routes/app.supplier.$id.tsx");
  "routes/app.supplier.$id._index": typeof import("./app/routes/app.supplier.$id._index.tsx");
  "routes/app.supplier.$id.config": typeof import("./app/routes/app.supplier.$id.config.tsx");
  "routes/app.supplier.$id.columns": typeof import("./app/routes/app.supplier.$id.columns.tsx");
  "routes/app.supplier.$id.price-rules": typeof import("./app/routes/app.supplier.$id.price-rules.tsx");
  "routes/app.supplier.$id.category-mapping": typeof import("./app/routes/app.supplier.$id.category-mapping.tsx");
  "routes/app.supplier.$id.preview": typeof import("./app/routes/app.supplier.$id.preview.tsx");
  "routes/app.supplier.$id.logs": typeof import("./app/routes/app.supplier.$id.logs.tsx");
  "routes/app.supplier.$id.import": typeof import("./app/routes/app.supplier.$id.import.tsx");
  "routes/app.tutorial": typeof import("./app/routes/app.tutorial.tsx");
  "routes/app.tutorial-dashboard": typeof import("./app/routes/app.tutorial-dashboard.tsx");
  "routes/app.tutorial-supplier.$section": typeof import("./app/routes/app.tutorial-supplier.$section.tsx");
  "routes/app.tutorial-settings": typeof import("./app/routes/app.tutorial-settings.tsx");
  "routes/app.tutorial-duplicates": typeof import("./app/routes/app.tutorial-duplicates.tsx");
  "routes/app.tutorial-queue": typeof import("./app/routes/app.tutorial-queue.tsx");
};